class AppStrings {
  static final Map<String, Map<String, String>> _texts = {
    'en': {
      'appTitle': 'Silent Scheduler',
      'home': 'Home',
      'addSchedule': 'Add Schedule',
      'history': 'History',
      'settings': 'Settings',
      'worldClock': 'World Clock',
      'title': 'Meeting Title',
      'date': 'Select Date',
      'startTime': 'Start Time',
      'endTime': 'End Time',
      'mode': 'Mode',
      'silent': 'Silent',
      'vibrate': 'Vibrate',
      'save': 'Save',
      'pleaseCompleteFields': 'Please complete all fields',
      'scheduleSaved': 'schedule saved successfully',
      'savedSchedules': 'Saved Schedules',
      'noSchedules': 'No schedules yet',
      'language': 'Language',
      'timezone': 'Timezone',
      'myTimezone': 'My Timezone',
      'notifications': 'Notifications',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'endTimeError': 'End time must be later than start time',
      'worldClocks': 'World Clocks',
    },
    'es': {
      'appTitle': 'Programador Silencioso',
      'home': 'Inicio',
      'addSchedule': 'Agregar Horario',
      'history': 'Historial',
      'settings': 'Configuración',
      'worldClock': 'Reloj Mundial',
      'title': 'Título de la reunión',
      'date': 'Seleccionar fecha',
      'startTime': 'Hora de inicio',
      'endTime': 'Hora de fin',
      'mode': 'Modo',
      'silent': 'Silencio',
      'vibrate': 'Vibración',
      'save': 'Guardar',
      'pleaseCompleteFields': 'Complete todos los campos',
      'scheduleSaved': 'horario guardado correctamente',
      'savedSchedules': 'Horarios guardados',
      'noSchedules': 'Aún no hay horarios',
      'language': 'Idioma',
      'timezone': 'Zona horaria',
      'myTimezone': 'Mi zona horaria',
      'notifications': 'Notificaciones',
      'enabled': 'Activado',
      'disabled': 'Desactivado',
      'endTimeError': 'La hora de fin debe ser posterior a la hora de inicio',
      'worldClocks': 'Relojes Mundiales',
    },
    'fil': {
      'appTitle': 'Silent Scheduler',
      'home': 'Home',
      'addSchedule': 'Magdagdag ng Iskedyul',
      'history': 'Kasaysayan',
      'settings': 'Mga Setting',
      'worldClock': 'Pandaigdigang Orasan',
      'title': 'Pamagat ng Meeting',
      'date': 'Pumili ng Petsa',
      'startTime': 'Oras ng Simula',
      'endTime': 'Oras ng Wakas',
      'mode': 'Mode',
      'silent': 'Silent',
      'vibrate': 'Vibrate',
      'save': 'I-save',
      'pleaseCompleteFields': 'Pakikumpleto ang lahat ng fields',
      'scheduleSaved': 'na-save na ang iskedyul',
      'savedSchedules': 'Mga Naka-save na Iskedyul',
      'noSchedules': 'Wala pang iskedyul',
      'language': 'Wika',
      'timezone': 'Timezone',
      'myTimezone': 'Aking Timezone',
      'notifications': 'Mga Notification',
      'enabled': 'Naka-on',
      'disabled': 'Naka-off',
      'endTimeError': 'Ang end time ay dapat mas huli kaysa start time',
      'worldClocks': 'Mga Pandaigdigang Orasan',
    },
    'ne': {
      'appTitle': 'साइलेन्ट स्केजुलर',
      'home': 'होम',
      'addSchedule': 'तालिका थप्नुहोस्',
      'history': 'इतिहास',
      'settings': 'सेटिङहरू',
      'worldClock': 'विश्व घडी',
      'title': 'बैठकको शीर्षक',
      'date': 'मिति चयन गर्नुहोस्',
      'startTime': 'सुरु समय',
      'endTime': 'समाप्ति समय',
      'mode': 'मोड',
      'silent': 'शान्त',
      'vibrate': 'भाइब्रेट',
      'save': 'सेभ गर्नुहोस्',
      'pleaseCompleteFields': 'कृपया सबै फिल्डहरू पूरा गर्नुहोस्',
      'scheduleSaved': 'तालिका सफलतापूर्वक सेभ भयो',
      'savedSchedules': 'सेभ गरिएका तालिकाहरू',
      'noSchedules': 'अहिलेसम्म कुनै तालिका छैन',
      'language': 'भाषा',
      'timezone': 'समय क्षेत्र',
      'myTimezone': 'मेरो समय क्षेत्र',
      'notifications': 'सूचनाहरू',
      'enabled': 'सक्रिय',
      'disabled': 'निष्क्रिय',
      'endTimeError': 'समाप्ति समय सुरु समयभन्दा पछाडि हुनुपर्छ',
      'worldClocks': 'विश्व घडीहरू',
      },
    };

  static String text(String lang, String key) {
    return _texts[lang]?[key] ?? _texts['en']![key] ?? key;
  }
}